### ISSUE TITLE
Require Linux/ARM64 Docker Image for coralogix/fluentd-coralogix-image

### ISSUE THREAD

**Issue by odidev** [coralogix/fluentd-coralogix-image#37]
Hi Team,

I am working with fluentd-coralogix-image on Linux/ARM64 platform.“[fluentd-coralogix-image](https://hub.docker.com/r/coralogixrepo/fluentd-coralogix-image)”  docker image is currently available for Linux/AMD64. It will be helpful if it gets available for the Linux/ARM64 as well.
 
I have successfully built the dockerimage for ARM64 via Travis-CI, using docker buildx utility, and successfully pushed to my Docker hub account. 

Please have a look at my changes[ here](https://github.com/odidev/fluentd-coralogix-image/pull/1/commits/a4655f315663cfa5e7093c1f224dbd2602aee5cd) .

Are you interested in releasing Linux/ARM64 docker image? If yes, I am happy to raise the PR with the changes shared in my commit. 
Please share your opinion on this.

**Comment by talknopf** [comment]
Hi @odidev,
Apologies for the late response.
we are currently deprecating this repository and moving to using this one insted:
https://github.com/coralogix/eng-integrations

the end result image is located here:
https://hub.docker.com/repository/docker/coralogixrepo/coralogix-fluentd-multiarch

Thank you for submitting this issue,
Tal.
